### ISSUE TITLE
Central Logout Not Working

### ISSUE THREAD

**Issue by kdbeall** [oktadeveloper/okta-play-oidc-example#1]
I get the following:
```Identity Provider: 
Error Code: illegal_post_logout_redirect_uri
Description: The 'post_logout_redirect_uri' parameter must be an absolute URI that is whitelisted in the client app settings.
```

**Comment by mraible** [comment]
You have to add your app’s URL to the Logout redirect URIs on Okta to fix this.

**Comment by kdbeall** [comment]
Thank you! @mraible

**Comment by wondercrazy15** [comment]
Hello 

Where to set 'post_logout_redirect_uri code or developer account?

**Comment by mraible** [comment]
You have to set it as a Logout redirect URI in your OIDC app in Okta.

**Comment by wondercrazy15** [comment]
Hello Mraible
Thank you for response.

I have added Logout redirect URIs in Okta.

![image](https://user-images.githubusercontent.com/30141700/50881099-94c7eb80-1406-11e9-8519-31431be460a7.png)

But It not Fixed. It Sample Given error.

![image](https://user-images.githubusercontent.com/30141700/50881171-d062b580-1406-11e9-86d3-23be7130fddc.png)

I have also Added trusted_origins 

![image](https://user-images.githubusercontent.com/30141700/50881212-f425fb80-1406-11e9-9780-39b6b451143c.png)

Is any other way to Solved.?
Is there need htttps?

**Comment by mraible** [comment]
Looking at your 400 screenshot (in the address bar), it shows that your Logout Redirect URI should be `http://localhost:49836/signout/callback`.

**Comment by vialvaga** [comment]
> Looking at your 400 screenshot (in the address bar), it shows that your Logout Redirect URI should be `http://localhost:49836/signout/callback`.

Merci @mraible, J'ai eu le meme probleme et cela est la solution.

**Comment by KostyaBatanin888** [comment]
Hi,

I have set the value correctly in my App

![image](https://user-images.githubusercontent.com/74581909/100565703-4b455a00-3318-11eb-87b7-b17cb2339434.png)

Based on what is in the URL when logging out:

https://dev-4003858.okta.com/oauth2/default/v1/logout?post_logout_redirect_uri=https%3A%2F%2Fsitecore-demo-rg-170970-single.azurewebsites.net%2Fidentity%2Fpostexternallogout%3Fnonce%3Dc6671394839644a8acbb6e928743ee4e%26ReturnUrl%3Dhttps%253a%252f%252fsitecore-demo-rg-170970-single.azurewebsites.net%252fidentity%252flogin%252fshell%252fSitecoreIdentityServer&id_token_hint=eyJraWQiOiJxVjdIUkpidHkwRkhkcDVYaXcwdlJhRTJoY1VEVkEwSEZMei1EODFhTFdrIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIwMHUxZGR6ZXJXNHlVdUVoZjVkNiIsInZlciI6MSwiaXNzIjoiaHR0cHM6Ly9kZXYtNDAwMzg1OC5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6IjBvYTFmMGtxNWxzMUNzcU5DNWQ2IiwiaWF0IjoxNjA2NzA2NDg0LCJleHAiOjE2MDY3MTAwODQsImp0aSI6IklELnhGR1NycHdna0JrSTJlSVZocExISGZsOVZJUHh1cXZRUXRSc2Jaek1KbTQiLCJhbXIiOlsicHdkIl0sImlkcCI6IjAwbzFkZHphejIzV2RuVXRDNWQ2Iiwibm9uY2UiOiI2Mzc0MjMwMzI4Mzg0MzQyNTguT0RZMk9UbGlZMlV0T1RRMVlTMDBaREF3TFdJME5qRXROalUxT0dJd056UTFPVGN5WVRka1pEWmhNakl0Tm1RMVpTMDBZbUppTFRsaU9UZ3RNbU14TWpRd01qY3laalJqIiwiYXV0aF90aW1lIjoxNjA2Njk2NzY0LCJhdF9oYXNoIjoid2dPWUt1VTdmdTZ5ZUdETTJ2SVduZyIsImNfaGFzaCI6IjIxWUlqMHhKbzFvTExiRnRwc1F2RWcifQ.ceS5Q7BQEH6WCiyjhS_ZJ-DCCyIx4y1rasTeij-o0b3RvqDowVhMS7PAxUr45fGp3PtpHRKgjogp9d-g6x2ANbr3ZkSvM48rUCJurPr9NXJlT822NsoL1NWCB9ZJaCeoAz4-CmP_zlJkRtPu1oHqBVDR2mHANmmDC3koj-iPrgOw-cBruMTedBoXkjpzOJ58-sgH3qE2i5vCTj0IZnC3IpfF8QC0NNeM0Pa2XeJ1LtspvsILmSBL8UwwHr-LYf72ci8Iw46gXU5BTeGi7tTZN4S8JXoDVgIUY1GIEHs9UiQzHwMy1sAY2-XHlYdm8eaUBz8K7I77X76Crhb0NMG9eg&x-client-SKU=ID_NET461&x-client-ver=5.3.0.0

![image](https://user-images.githubusercontent.com/74581909/100565828-86e02400-3318-11eb-825b-6ca91bb94f1f.png)


But I am still having the same issue. Please help if you can.

Thank you.

**Comment by mraible** [comment]
Please send your issues to developers@okta.com. This issue is not monitored by developer support.

**Comment by abdellahgrib** [comment]
In my case I commented out the `AuthenticationProperties` that contains `RedirectUri`. This code was in my C# (MVC) Action !

```
HttpContext.GetOwinContext().Authentication.SignOut(
    //new AuthenticationProperties { RedirectUri = "/logout" },
    OpenIdConnectAuthenticationDefaults.AuthenticationType,
    CookieAuthenticationDefaults.AuthenticationType );
```

This worked for me. Hope this could help!

Note that I specify the URI, which is in Okta Logout redirect URIs section, elsewhere in the code (startup configuration).
