### ISSUE TITLE
404s on index and logout routes

### ISSUE THREAD

**Issue by macfisher** [oktadeveloper/okta-play-oidc-example#3]
It seems like `localhost:9000` should route to `/` and that should serve a page with a link to the protected page, however this returns a 404.

Also, the /logout route returns a 404. Is this expected or is this a bug? How can I verify that the security configuration class (SecurityModule) is working?

**Comment by mraible** [comment]
Are you using the same version of libraries that this example uses? [Add Authentication to Play Framework with OIDC and Okta](https://developer.okta.com/blog/2017/10/31/add-authentication-to-play-framework-with-oidc) is the tutorial I used to create this example.

**Comment by macfisher** [comment]
Bare with me, I am very new to sbt. I simply pulled your repo and followed the instructions to run it and it doesn't work. I have not changed anything in the build.sbt or anything for that matter.
```
name := "play-oauth2"

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayJava)

scalaVersion := "2.11.2"

libraryDependencies ++= Seq(
  cache,
  javaWs,
  "org.springframework" % "spring-aop" % "4.0.3.RELEASE",
  "org.springframework" % "spring-expression" % "4.0.3.RELEASE",
  "org.springframework" % "spring-test" % "4.0.3.RELEASE",
  "org.springframework.security" % "spring-security-config" % "3.2.3.RELEASE",
  "org.springframework.security" % "spring-security-core" % "3.2.3.RELEASE",
  "org.springframework.security.oauth" % "spring-security-oauth2" % "2.0.2.RELEASE"
)

EclipseKeys.withSource := true

**Comment by mraible** [comment]
I was able to clone this repo and make it work this morning. I had to use Java 8. I used [SDKMAN](https://sdkman.io/) to install it and sbt.

```
sdk install java 8.0.202-amzn
sdk install sbt
```
